repos:
  - repo: https://github.com/pycqa/isort
    rev:  5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.11
        args: ["."]
