[tool.ruff]
target-version = "py38"
line-length =  88
exclude = [
    ".git",
    ".ruff_cache",
    "parse_docs.py"
]
include = ["pyproject.toml", "src/*.py",]


[tool.ruff.lint]
ignore = ["E741", "E402", "F403", "F405"] # ignore ambigous import rules
